<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>10</LangVersion>
        <EnableHarmony>true</EnableHarmony>

        <!-- Manifest fields -->
        <Name>BasketMod</Name>
        <Authors>EternalSoap</Authors>
        <Description>Adds usable baskets to the game</Description>
        <UniqueID>EternalSoap.BasketMod</UniqueID>
        <MinimumGameVersion>1.6</MinimumGameVersion>
        <MinimumApiVersion>4.5.2</MinimumApiVersion>
        <Version>1.0.4</Version>
        <UpdateKeys>Nexus:45590</UpdateKeys>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Leclair.Stardew.ModManifestBuilder" Version="2.4.1"/>
        <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0"/>
    </ItemGroup>

    <ItemGroup>
        <ContentPacks Include="[CP] $(name)" Version="$(Version)" />
    </ItemGroup>
</Project>